insert into jabberuser (
    values (0, 'donaldjtrump', 'imnotOrange100', 'donald@donald.com'),
           (1, 'kim', 'Yeisgreat2', 'kim@kanye.com'),
           (2, 'davidbowie', 'davidB', 'david@bowienet.com'),
           (3, 'hackertdog', 'whatsupdawg', 'hackert@dog.com'),
           (4, 'robertsmith', 'robbie', 'rob@thecure.com'),
           (5, 'klopp', 'ploop', 'manager@anfield.com'),
           (6, 'percy', 'jackson', 'ppig@marksandspencer.net'),
           (7, 'cyborg', 'ttgo5', 'cyborg@teentitansgo.com'),
           (8, 'icebear', 'brownbear', 'iceb@wbb.com'),
           (9, 'solesurvivor', 'onlyone1', 'sole@vault111.com'),
           (10, 'ellie', 'lastofus2', 'ellie@lastofus.com'),
           (11, 'jumpman', 'supermario', 'jumpmanmario@marioworld.net'),
           (12, 'edballs', 'eddie', 'ed@edballs.com')
);

insert into jab(
    values(0, 0, 'MAGA!'),
    (1, 0, 'SAD!'),
    (2, 1, 'uokhun'),
    (3, 2, 'My version of The Man Who Sold The World is way better'),
    (4, 3, 'WOOF!'),
    (5, 0, 'covfefe'),
    (6, 12, 'Ed Balls'),
    (7, 7, 'anybody watching that Gumball show?'),
    (8, 8, 'ice bear says We Bare Bears is the best show'),
    (9, 11, 'coming for you, Donkey Kong!!!'),
    (10, 9, 'Mmm, roasted mirelurk for lunch.'),
    (11, 3, 'WOOF!!!')
);

insert into follows(
    values(1,2),
    (11,2),
    (0,12),
    (0,11),
    (0,6),
    (0,7),
    (1,3),
    (1,0),
    (1,12),
    (2,0),
    (2,9),
    (3,1),
    (3,7),
    (3,8),
    (6,0),
    (6,8),
    (6,10),
    (7,0),
    (7,3),
    (9,1),
    (9,4),
    (9,11),
    (11,0),
    (11,12),
    (12,11),
    (12,0),
    (0,0),
    (1,1),
    (2,2),
    (3,3),
    (4,4),
    (5,5),
    (6,6),
    (7,7),
    (8,8),
    (9,9),
    (10,10),
    (11,11),
    (12,12)
);

insert into likes (
    values(0,2),
    (2,3),
    (0,4),
    (0,11),
    (1,2),
    (1,6),
    (3,3),
    (3,11),
    (4,10),
    (10,0),
    (7,0),
    (10,10)
);